[build]
	publish = "dist/"
	command = "hugo -v -s source/ -d ../dist --baseURL $URL"

[build.environment]
	HUGO_VERSION = "0.46"

[context.deploy-preview]
	command = "hugo -v -s source/ -d ../dist --baseURL $DEPLOY_PRIME_URL"