# --------------------------------
# CONFIG: Site settings
# --------------------------------

title: "Carlos Melegrito"
description: "Carlos is a computer science student and designer."
url: http://mlgrto.com/
color: "#7B72E9"

markdown: kramdown
permalink: pretty

sass:
  style: compressed

collections:
  projects:
    title: Projects
    output: true
  posts:
    title: Posts
    output: true

defaults:
- scope:
    path: ''
    type: posts
  values:
    title: Untitled
    subtitle: Currently being written
    layout: default
- scope:
    path: ''
    type: projects
  values:
    title: Untitled
    layout: default
    permalink: "/work/:title"
    images:
    - /static/images/placeholder.jpg
    - /static/images/placeholder.jpg